export const menu = [
  {
    key:'首页',
    path:'list-home',
    icon:require('../assets/u135.png'),
  },
  {
    key:'商家',
    path:'list-seller',
    icon:require('../assets/u127.png'),
  },
  {
    key:'会员',
    path:'list-member',
    icon:require('../assets/u127.png'),
  },
  {
    key:'促销',
    path:'list-sales',
    icon:require('../assets/u123.png'),
  },
  {
    key:'运营',
    path:'list-operate',
    icon:require('../assets/u125.png'),
  },
  {
    key:'商品',
    path:'list-goods',
    icon:require('../assets/u124.png'),
  },
  {
    key:'统计',
    path:'list-count',
    icon:require('../assets/u137.png'),
  },
  {
    key:'财务',
    path:'list-financ',
    icon:require('../assets/u130.png'),
  },
  {
    key:'设置',
    path:'list-set',
    icon:require('../assets/u133.png'),
  },
  {
    key:'权限',
    path:'list-power',
    icon:require('../assets/u134.png'),
  },
];
export const MenuChilren = [
  [
    {
      title:'首页',
      keyword:'list-home',
      children:[
        {
          key:'系统首页',
          path:'list-power',
        },
        {
          key:'账户设置',
          path:'list-power',
        },
        {
          key:'登录日志',
          path:'list-power',
        }
      ]
    }
  ],
  [
    {
      title:'商家管理',
      keyword:'list-seller',
      children:[
        {
          key:'商家列表',
          path:'list-power',
          route:'/business/businesslist'
        },
      ]
    }
  ],
  [
    {
      title:'会员管理',
      keyword:'list-member',
      children:[
        {
          key:'会员列表',
          path:'list-power',
        },
        {
          key:'购买力筛选',
          path:'list-power',
        },
        {
          key:'标签管理',
          path:'list-power',
        },
        {
          key:'会员登记设置',
          path:'list-power',
        },
      ]
    },
    {
      title:'成长值及蝌蚪值',
      keyword:'list-member',
      children:[
        {
          key:'成长值及蝌蚪币查询',
          path:'list-power',
        },
        {
          key:'任务奖励设置',
          path:'list-power',
        },
        {
          key:'更多规则设置',
          path:'list-power',
        },
      ]
    }
  ],
  [
    {
      title:'秒杀专区',
      keyword:'list-sales',
      children:[
        {
          key:'秒杀活动列表',
          path:'list-power',
        },
        {
          key:'时间段列表',
          path:'list-power',
        },
        {
          key:'秒杀提醒通知',
          path:'list-power',
        },
      ]
    },
    {
      title:'优惠券管理',
      keyword:'list-sales',
      children:[
        {
          key:'优惠券列表',
          path:'list-power',
        },
        {
          key:'添加优惠券',
          path:'list-power',
        },
      ]
    },
    {
      title:'活动管理',
      keyword:'list-sales',
      children:[
        {
          key:'活动列表',
          path:'list-power',
        },
        {
          key:'添加活动',
          path:'list-power',
        },
      ]
    },
    {
      title:'首页推荐',
      keyword:'list-sales',
      children:[
        {
          key:'品牌制造商',
          path:'list-power',
        },
        {
          key:'新鲜好物',
          path:'list-power',
        },
        {
          key:'人气推荐',
          path:'list-power',
        },
        {
          key:'专题精选',
          path:'list-power',
        },
      ]
    }
  ],
  [
    {
      title:'直播管理',
      keyword:'list-operate',
      children:[
        {
          key:'直播列表',
          path:'list-power',
        },
      ]
    },
    {
      title:'消息查询',
      keyword:'list-operate',
      children:[
        {
          key:'系统消息',
          path:'list-power',
        },
        {
          key:'短信消息',
          path:'list-power',
        },
        {
          key:'站内信消息',
          path:'list-power',
        },{
          key:'app推送消息',
          path:'list-power',
        },

      ]
    },
    {
      title:'其他查询',
      keyword:'list-operate',
      children:[
        {
          key:'优惠券查询',
          path:'list-power',
        },
        {
          key:'邀请好友查询',
          path:'list-power',
        },
        {
          key:'幸运抽奖查询',
          path:'list-power',
        }
      ]
    },
    {
      title:'广告管理',
      keyword:'list-operate',
      children:[
        {
          key:'广告列表',
          path:'list-power',
        },
        {
          key:'添加广告',
          path:'list-power',
        }
      ]
    }
  ],
  [
    {
      title:'商品管理',
      keyword:'list-goods',
      children:[
        {
          key:'商品分类',
          path:'list-power',
        },
      ]
    }
  ],
  [
    {
      title:'统计分析',
      keyword:'list-count',
      children:[
        {
          key:'交易统计',
          path:'list-power',
        },
        {
          key:'流量统计',
          path:'list-power',
        },
        {
          key:'商品统计',
          path:'list-power',
        },
        {
          key:'会员统计',
          path:'list-power',
        },
        {
          key:'搜索统计',
          path:'list-power',
        },
      ]
    }
  ],
  [
    {
      title:'财务报表',
      keyword:'list-financ',
      children:[
        {
          key:'综合统计',
          path:'list-power',
        },
        {
          key:'会员排行',
          path:'list-power',
        },
        {
          key:'销售统计',
          path:'list-power',
        }
      ]
    },
    {
      title:'对账管理',
      keyword:'list-financ',
      children:[
        {
          key:'对账列表',
          path:'list-power',
        }
      ]
    }
  ],
  [
    {
      title:'平台设置',
      keyword:'list-set',
      children:[
        {
          key:'平台信息',
          path:'list-power',
        },
        {
          key:'基本设置',
          path:'list-power',
        },
        {
          key:'消息提醒',
          path:'list-power',
        },
        {
          key:'验证码设置',
          path:'list-power',
        }
      ]
    },
    {
      title:'支付配送',
      keyword:'list-set',
      children:[
        {
          key:'运费模板',
          path:'list-power',
        },
        {
          key:'物流公司',
          path:'list-power',
        },
        {
          key:'支付设置',
          path:'list-power',
        },
        {
          key:'区域管理',
          path:'list-power',
        }
      ]
    }
  ],
  [
    {
      title:'权限管理',
      keyword:'list-power',
      children:[
        {
          key:'部门管理',
          path:'list-power',
        },
        {
          key:'成员管理',
          path:'list-power',
        },
        {
          key:'客服管理',
          path:'list-power',
        },
        {
          key:'操作日志',
          path:'list-power',
        },
        {
          key:'数据库管理',
          path:'list-power',
        },
      ]
    }
  ],
]
